name: "Atualizar HelpSinge"

on:
  schedule:
    - cron: "0 3 * * *"  # Todo dia às 03:00 UTC
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  update-helpsinge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install

      - name: Run scraper
        run: |
          npm run scrape
